### ISSUE TITLE
this distribution has two issue trackers

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/module-build-tiny#18]
The github issues queue is non-empty, and so is https://rt.cpan.org/Dist/Display.html?Name=Module-Build-Tiny -- which do you prefer?

**Comment by Leont** [comment]
I've been planning to switch most of my dists in this direction for some time now, but I haven't actually done so yet (github matches my workflow better, but I do dislike the lack over an overview page).

**Comment by jsoref** [comment]
It looks like you've filled configured CPAN:

> Preferred bug tracker
> Please visit the [preferred bug tracker](https://github.com/Perl-Toolchain-Gang/module-build-tiny/issues) to report your issue.

So, I think this ticket can be resolved.
