### ISSUE TITLE
qr// differs depending on perl versions

### ISSUE THREAD

**Issue by skaji** [Perl-Toolchain-Gang/module-build-tiny#34]
From https://github.com/miyagawa/cpanminus/issues/668

While Module::Build::Tiny uses qr//,
the meaning of qr// may be different on perl5.16- and perl5.18+. See https://github.com/Perl/perl5/issues/11549

It would be nice Module::Build::Tiny considers this difference.
I think qr/(?^:)/ consistently represents an empty string on any perl versions.

**Comment by Leont** [comment]
The caret is a 5.14-ism, but `qr/(?:)/` should work on any version

**Comment by Leont** [comment]
Released

**Comment by skaji** [comment]
@Leont Thanks!
